"""Allowlisted delivery for the embodied-body stage: no credentials, no big archives."""
from pathlib import Path
import hashlib
import json
import shutil

SRC = Path(__file__).resolve().parent
DST = Path('/home/sensen/Desktop/cell_wound_prototype/embodied_body')

FILES = [
    'setup_body_env.sh',
    'probe_body_backend.py',
    'run_body_walk.py',
    'run_body_selftest.py',
    'engine/embodied/__init__.py',
    'engine/embodied/body_backend.py',
    'outputs/embodied_body/ROUND8_EMBODIED_M1.md',
    'outputs/embodied_body/ROUND9_BASELINE_FIXES.md',
    'outputs/embodied_body/ROUND10_CLOSED_LOOP.md',
    'engine/embodied/plasticity.py',
    'run_plasticity_ablation.py',
    'run_plasticity_selftest.py',
    'make_status_report.py',
    'run_behaviour_acceptance.py',
    'render_stills.py',
    'outputs/embodied_body/behaviour_acceptance.json',
    'outputs/embodied_body/slowphys_report.json',
    'outputs/embodied_body/slowphys_demo.png',
    'engine/embodied/slow_physiology.py',
    'run_embodied_slowphys.py',
    'run_embodied_slowphys_selftest.py',
    'outputs/embodied_body/STATUS_FOUR_COLUMNS.md',
    'outputs/embodied_body/STATUS_FOUR_COLUMNS.json',
    'outputs/embodied_body/plasticity_selftest.json',
    'outputs/embodied_body/plasticity_report.json',
    'outputs/embodied_body/plasticity_ablation.png',
    'outputs/embodied_body/ROUND11_PLASTICITY.md',
    'outputs/embodied_body/ROUND12_ABLATION.md',
    'outputs/embodied_body/ROUND13_FINAL_ASSESSMENT.md',
    'outputs/embodied_body/ROUND12_SLOWPHYS.md',
    'outputs/embodied_body/stills_touch/xray_touch_combined.png',
    'outputs/embodied_body/stills_touch/xray_touch_report.json',
    'outputs/embodied_body/stills_touch/xray_touch_t1.0s.png',
    'outputs/embodied_body/stills_touch/xray_touch_t2.0s.png',
    'outputs/embodied_body/stills_touch/xray_touch_t3.1s.png',
    'outputs/embodied_body/stills_touch/xray_touch_t4.1s.png',
    'outputs/embodied_body/stills/baseline_t0s.png',
    'outputs/embodied_body/stills/baseline_t1s.png',
    'outputs/embodied_body/stills/baseline_t2s.png',
    'outputs/embodied_body/stills/baseline_t3s.png',
    'outputs/embodied_body/stills/baseline_t4s.png',
    'outputs/embodied_body/stills/filmstrip_world.png',
    'outputs/embodied_body/stills/neural_t0s.png',
    'outputs/embodied_body/stills/neural_t1s.png',
    'outputs/embodied_body/stills/neural_t2s.png',
    'outputs/embodied_body/stills/neural_t3s.png',
    'outputs/embodied_body/stills/neural_t4s.png',
    'outputs/embodied_body/stills/side_by_side_baseline_vs_neural.png',
    'outputs/embodied_body/stills/track_00_t0.0s.png',
    'outputs/embodied_body/stills/track_01_t1.0s.png',
    'outputs/embodied_body/stills/track_02_t2.2s.png',
    'outputs/embodied_body/stills/track_03_t3.4s.png',
    'outputs/embodied_body/stills/track_04_t4.6s.png',
    'outputs/embodied_body/stills/track_05_t5.8s.png',
    'outputs/embodied_body/stills/world_00_t0.0s.png',
    'outputs/embodied_body/stills/world_01_t1.0s.png',
    'outputs/embodied_body/stills/world_02_t2.2s.png',
    'outputs/embodied_body/stills/world_03_t3.4s.png',
    'outputs/embodied_body/stills/world_04_t4.6s.png',
    'outputs/embodied_body/stills/world_05_t5.8s.png',
    'outputs/embodied_body/slowphys_episode.npz',
    'outputs/embodied_body/slowphys_traces.npz',
    'outputs/embodied_body/slowphys_selftest.json',
    'outputs/embodied_body/banc_fafb_reconciliation.json',
    'outputs/embodied_body/loop_round1_report.md',
    'outputs/embodied_body/loop_selftest.json',
    'outputs/embodied_body/loop_neural_walk_seed0.mp4',
    'outputs/embodied_body/loop_frame_montage.png',
    'outputs/embodied_body/loop_episode_cpg_baseline_seed0.npz',
    'outputs/embodied_body/loop_episode_neural_modulated_seed0.npz',
    'outputs/embodied_body/body_env_versions.json',
    'outputs/embodied_body/body_backend_probe.json',
    'outputs/embodied_body/body_walk_report.json',
    'outputs/embodied_body/body_walk_montage.png',
    'outputs/embodied_body/body_walk_seed0.mp4',
    'outputs/embodied_body/body_selftest.json',
    'outputs/embodied_body/body_walk_traces.npz',
    'run_receptor_unit_selftest.py',
    'engine/embodied/loop.py',
    'engine/embodied/adapters.py',
    'run_embodied_loop.py',
    'run_embodied_loop_selftest.py',
    'outputs/embodied_body/receptor_unit_selftest.json',
    'outputs/embodied_body/loop_report.json',
    'outputs/embodied_body/loop_comparison.png',
    'outputs/brain_isolation/EVIDENCE_LEDGER.md',
    'run_vision_quicklook.py',
    'outputs/embodied_body/vision_quicklook.png',
    'outputs/embodied_body/vision_quicklook.json',
    'engine/embodied/scene.py',
    'engine/embodied/vision.py',
    'run_scene_selftest.py',
    'outputs/embodied_body/scene_selftest.json',
    'run_vision_nondegeneracy.py',
    'outputs/embodied_body/vision_nondegeneracy.png',
    'outputs/embodied_body/vision_nondegeneracy.json',
    'outputs/embodied_body/SCENE_PARAMETER_PROVENANCE.md',
    'outputs/embodied_body/ROUND15_SCENE_VISION.md',
    'run_scene_vision_integration.py',
    'outputs/embodied_body/scene_vision_integration.png',
    'outputs/embodied_body/scene_vision_integration.json',
    'outputs/embodied_body/mujoco_docs_raw.md',
    'outputs/embodied_body/vision_sources_raw.md',
    'outputs/embodied_body/scene_blank_wide.png',
    'outputs/embodied_body/scene_natural_wide.png',
    'outputs/embodied_body/scene_blank_close.png',
    'engine/embodied/natural_scene.py',
    'run_natural_scene.py',
    'outputs/embodied_body/natural_scene.json',
    'outputs/embodied_body/natural_scene_overview.png',
    'outputs/embodied_body/natural_scene_spectra.png',
    'outputs/embodied_body/SCENE_REALISM_AUDIT.md',
    'outputs/embodied_body/scene_realism_audit.json',
    'outputs/embodied_body/scene_realism_audit.png',
    'outputs/embodied_body/ROUND16_NATURAL_SCENE.md',
    'outputs/embodied_body/ROUND17_VISION_TIER_FEASIBILITY.md',
    'outputs/embodied_body/ROUND18_VISUAL_ROUTE_IN_TIER.md',
    'outputs/embodied_body/ROUND19_PERIODICITY_ARBITRATION.md',
    'arbitrate_periodicity.py',
    'outputs/embodied_body/arbitrate_periodicity.json',
    'outputs/embodied_body/arbitrate_periodicity.png',
    'run_vision_into_tier.py',
    'outputs/embodied_body/vision_into_tier.json',
    'outputs/embodied_body/vision_into_tier.png',
    'outputs/embodied_body/scene_natural_close.png',
    'verify_natural_scene.py',
    'compare_ground_audit_instruments.py',
    'scene_realism_audit_run.py',
    'outputs/embodied_body/compare_ground_audit_view.png',
    'outputs/embodied_body/compare_ground_audit_instruments.json',
    'outputs/embodied_body/verify_natural_scene.png',
    'outputs/embodied_body/verify_natural_scene.json',
    'outputs/embodied_body/scene_realism_audit_summary.png',
    'outputs/embodied_body/assets/natural_ground_photo.png',
    'outputs/embodied_body/assets/natural_ground_photo.provenance.json',
    'outputs/embodied_body/vision_nondegeneracy_series.npz',
    'engine/params.py',
    'engine/electrode.py',
    'engine/electrode_damage.py',
    'engine/cable.py',
    'engine/neural_active.py',
    'engine/local_tissue.py',
    'engine/injury_tissue.py',
    'engine/neck_cut_data.py',
    'engine/synapse_map.py',
    'engine/receptors.py',
    'engine/neural_cond.py',
    'engine/neural_hist.py',
    'engine/touch_damage_scenario.py',
    'engine/isolation_scenario.py',
    'engine/multirate_scenario.py',
    'engine/da_protocol.py',
    'engine/graded_vision.py',
    'engine/embodied/access_map.py',
    'engine/electrode_frontend.py',
    'engine/electrode_stim.py',
    'engine/electrode_tissue.py',
    'run_electrode_damage.py',
    'run_electrode_damage_selftest.py',
    'run_electrode_frontend.py',
    'run_electrode_selftest.py',
    'run_electrode_stim.py',
    'run_electrode_tissue.py',
    'run_touch_damage_scenario.py',
    'run_touch_damage_selftest.py',
    'run_local_electrode_demo.py',
    'run_neural_recording_demo.py',
    'outputs/embodied_body/ROUND14_VISION_AND_SCENE.md',
    'outputs/embodied_body/ROUND20_TASK_D_RESULT.md',
    'outputs/embodied_body/ROUND21_EDGE_CONVENTION_CORRECTION.md',
    'outputs/embodied_body/ROUND22_READOUT_DEGREE_FIX.md',
    'outputs/embodied_body/ROUND23_ACCESS_MAP_BLOCKER.md',
    'outputs/embodied_body/ROUND24_BANC_SOMA_COORDS.md',
    'outputs/embodied_body/ROUND25_ACCESS_MAP_VERIFIED.md',
    'outputs/embodied_body/ROUND26_NEW_GEOMETRY.md',
    'run_access_map.py',
    'make_scene_audit_figure.py',
    'outputs/embodied_body/access_map.json',
    'outputs/embodied_body/access_map.png',
    'outputs/embodied_body/electrode_frontend.json',
    'outputs/embodied_body/electrode_frontend.png',
    'outputs/embodied_body/electrode_stim.json',
    'outputs/embodied_body/electrode_stim.png',
    'outputs/embodied_body/electrode_tissue.json',
    'outputs/embodied_body/electrode_tissue.png',
    'engine/electrode_recording.py',
    'run_electrode_recording.py',
    'run_recording_physics_regression.py',
    'run_frontend_regression.py',
    'engine/electrode_sorting.py',
    'run_electrode_sorting.py',
    'outputs/embodied_body/electrode_recording.json',
    'outputs/embodied_body/electrode_recording.png',
    'outputs/embodied_body/electrode_sorting.json',
    'outputs/embodied_body/electrode_sorting.png',
    'outputs/embodied_body/RECORDING_CORRECTIONS.md',
    'outputs/embodied_body/RECORDING_ARCHITECTURE.md',
    'outputs/embodied_body/RECORDING_INDEPENDENT_AUDIT.md',
    'outputs/embodied_body/VIRTUAL_BODY_RECORDING_DESIGN.md',
]


def main():
    DST.mkdir(parents=True, exist_ok=True)
    manifest, missing = [], []
    for rel in FILES:
        src = SRC / rel
        if not src.is_file():
            missing.append(rel)
            continue
        dst = DST / rel
        dst.parent.mkdir(parents=True, exist_ok=True)
        if src.is_symlink():
            raise RuntimeError('symlink in delivery list: %s' % rel)
        shutil.copy2(src, dst)
        data = dst.read_bytes()
        manifest.append({'path': rel, 'bytes': len(data),
                         'sha256': hashlib.sha256(data).hexdigest()})
    report = {
        'stage': 'embodied body, milestone 1: a physical fly that walks',
        'status': 'hand-built research prototype; the controller is FlyGym demo CPG '
                  '(ENGINEERING BASELINE), NOT connectome-driven',
        'how_to_run': {
            'environment': 'this delivery needs the separate BODY environment, which is '
                           'NOT included. Recreate it with setup_body_env.sh '
                           '(flygym==2.1.0, mujoco>=3.9,<3.10) and run with its python.',
            'walk': './venv_body/bin/python run_body_walk.py --seeds 0,1,2,3,4,5,6,7,8,9 --seconds 10',
            'tests': './venv_body/bin/python run_body_selftest.py',
            'probe': './venv_body/bin/python probe_body_backend.py',
        },
        'not_included_and_why': [
            'the venv_body environment itself (binary, large)',
            'FlyGym/MuJoCo assets (installed with the packages)',
            'any credential file: none is read by this stage and none is copied',
        ],
        'units_warning': 'model units are MILLIMETRES; distances are not metres',
        'files': manifest, 'missing_optional_files': missing,
        'credentials': 'explicit allowlist; no cookie/token file is present or copied',
    }
    (DST / 'MANIFEST.json').write_text(json.dumps(report, indent=2))
    print('Delivered', len(manifest), 'files to', DST)
    print('Missing:', missing)


if __name__ == '__main__':
    main()
