/* Project-service replay viewer. Body-attached similarity maps are schematic, not registration.
 * Playback is normalized across independent clocks; recording jobs do not drive scene physics. */
(function () {
'use strict';
const $ = id => document.getElementById(id), D = window.VIEWER_DATA || {}, MAX = 12000;
const errors = window.viewerErrors = window.viewerErrors || [];
const list = x => Array.isArray(x) ? x : [], finite = (v,d=0) => Number.isFinite(Number(v)) ? Number(v) : d;
const txt = x => typeof x === 'string' ? x : JSON.stringify(x == null ? '未提供' : x);
const B=D.body||{}, N=D.neural||{}, E=D.electrodes||{}, C=D.calcium||{};
function element(tag,text,parent){const e=document.createElement(tag);e.textContent=text;if(parent)parent.appendChild(e);return e;}
const missing = !window.VIEWER_DATA;
if (!window.THREE) { $('status').textContent='本地 Three.js 未加载；请保留 vendor 文件夹。'; errors.push('THREE unavailable'); return; }
const T=window.THREE, scene=new T.Scene(), camera=new T.PerspectiveCamera(43,1,.000001,10000);
let renderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true});}catch(e){errors.push(e.message);$('status').textContent='WebGL 不可用：'+e.message;return;}
renderer.setPixelRatio(Math.min(window.devicePixelRatio||1,1.5));renderer.outputEncoding=T.sRGBEncoding;$('viewport').appendChild(renderer.domElement);
scene.add(new T.HemisphereLight(0xd3edff,0x253244,1.5)); const light=new T.DirectionalLight(0xffffff,.8);light.position.set(5,8,10);scene.add(light);
const layers={}, picks=[], labels=[], selectionRing=new T.Mesh(new T.SphereGeometry(1,12,8),new T.MeshBasicMaterial({color:0xffffff,wireframe:true,depthTest:false}));selectionRing.visible=false;scene.add(selectionRing);
const bodyMats=[],bodyObjects=[],electrodeObjects=[];let neuralPoints,calciumPoints,selected=null,progress=0,playing=false,lastTime=0,focusName='all';
function group(name){const g=new T.Group();scene.add(g);layers[name]=g;return g;}group('body');group('neural');group('electrodes');group('calcium');
function good(p){return Array.isArray(p)&&p.length>=3&&p.slice(0,3).every(v=>Number.isFinite(Number(v)));}
const nodeData=list(B.nodes).slice(0,MAX), neuralPos=list(N.positions_um).slice(0,MAX), electrodePos=list(E.positions_um).slice(0,256), calciumPos=list(C.positions_um).slice(0,MAX);
function bounds(positions,scale=1){const box=new T.Box3();positions.forEach(p=>{if(good(p))box.expandByPoint(new T.Vector3(...p.slice(0,3).map(v=>Number(v)*scale)));});if(box.isEmpty())box.set(new T.Vector3(-.05,-.05,-.05),new T.Vector3(.05,.05,.05));return {box,center:box.getCenter(new T.Vector3()),size:Math.max(...box.getSize(new T.Vector3()).toArray(),.01)};}
const bb=bounds(nodeData.filter(n=>n.name!=='world').map(n=>n.position)), nb=bounds(neuralPos.concat(electrodePos, [E.reference_um,E.return_um].filter(good)),.001), cb=bounds(calciumPos,.001);const bodyRoot=good(nodeData[1]?.position)?new T.Vector3(...nodeData[1].position):bb.center.clone();
const span=Math.max(bb.size,nb.size,cb.size,.2), region={body:new T.Vector3()};
// The rig is separate from layer visibility: hiding body context must not hide internals.
const rig=new T.Group();scene.add(rig);rig.position.copy(bb.center).negate();rig.add(layers.body);
function worldLabel(name,pos,description,parent=layers[name]){const e=element('div',description,$('scene-labels'));e.className='world-label';labels.push({name,pos,parent,e});}
worldLabel('body',bb.center.clone().add(new T.Vector3(0,-bb.size*.62,0)),'身体 · mm · 回放上下文');
const sphere=new T.SphereGeometry(1,16,12);
nodeData.forEach((n,i)=>{if(n.name==='world'||!good(n.position))return;const mat=new T.MeshPhongMaterial({color:0x729eb4,transparent:true,opacity:.23,depthWrite:false});bodyMats.push(mat);const o=new T.Mesh(sphere,mat);o.position.fromArray(n.position);o.scale.setScalar(Math.max(finite(n.radius_mm,.03),.001));o.userData={kind:'body',index:i};layers.body.add(o);bodyObjects.push(o);picks.push(o);});
const bodyMeshes=[];list(B.meshes).slice(0,500).forEach(m=>{const local=list(m.local_vertices_mm).flat(),verts=local.length?local:list(m.vertices_mm).flat();if(verts.length<9)return;const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));if(list(m.indices).length)g.setIndex(m.indices);g.computeVertexNormals();const mat=new T.MeshPhongMaterial({color:0x98b8c9,transparent:true,opacity:.26,side:T.DoubleSide,depthWrite:false});const o=new T.Mesh(g,mat);o.userData={kind:'body',index:finite(m.body_index),meshName:m.name};if(local.length){const n=nodeData[o.userData.index];if(n&&good(n.position))o.position.fromArray(n.position);}layers.body.add(o);bodyMats.push(mat);picks.push(o);bodyMeshes.push({o,local:!!local.length,index:o.userData.index});});
const linkVertices=[];list(B.links).forEach(l=>{const a=nodeData[l[0]],b=nodeData[l[1]];if(a&&b&&a.name!=='world'&&b.name!=='world'&&good(a.position)&&good(b.position))linkVertices.push(...a.position,...b.position);});const linkGeometry=new T.BufferGeometry();linkGeometry.setAttribute('position',new T.Float32BufferAttribute(linkVertices,3));const bodyLinks=new T.LineSegments(linkGeometry,new T.LineBasicMaterial({color:0x73c1d6,transparent:true,opacity:.5}));layers.body.add(bodyLinks);
function points(positions,g,kind,size){const valid=positions.map((v,i)=>good(v)?i:-1).filter(i=>i>=0),p=new Float32Array(valid.length*3),colors=new Float32Array(valid.length*3);valid.forEach((index,i)=>{p.set(positions[index].slice(0,3).map(x=>x*.001),i*3);colors.set([.25,.8,.9],i*3);});const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(p,3));geo.setAttribute('color',new T.BufferAttribute(colors,3));const o=new T.Points(geo,new T.PointsMaterial({size,vertexColors:true,sizeAttenuation:true,transparent:false,opacity:1}));o.userData={kind,indices:valid};g.add(o);picks.push(o);return o;}
neuralPoints=points(neuralPos,layers.neural,'neural',nb.size*.012);calciumPoints=points(calciumPos,layers.calcium,'calcium',cb.size*.025);
const electrodeDiameter=finite(E.diameter_um,7)*.001,shaftLength=Math.max(nb.size*.42,.07);const shaftGeo=new T.CylinderGeometry(electrodeDiameter/2,electrodeDiameter/2,shaftLength,10);shaftGeo.rotateX(Math.PI/2);
electrodePos.forEach((p,i)=>{if(!good(p))return;const o=new T.Mesh(shaftGeo,new T.MeshPhongMaterial({color:0xe5ba65}));o.position.fromArray(p.map(v=>v*.001));o.position.z+=shaftLength/2;o.userData={kind:'electrodes',index:i,base:p.map(v=>v*.001)};layers.electrodes.add(o);electrodeObjects.push(o);picks.push(o);});
[['reference_um',0xc29cff,'参考'],['return_um',0x82df98,'回流']].forEach(([key,col,label])=>{if(!good(E[key]))return;const o=new T.Mesh(new T.OctahedronGeometry(Math.max(nb.size*.02,.01)),new T.MeshPhongMaterial({color:col}));o.position.fromArray(E[key].map(v=>v*.001));layers.electrodes.add(o);worldLabel('electrodes',o.position.clone(),label+' · 示意标记放大');});
const arrow=new T.ArrowHelper(new T.Vector3(0,0,-1),new T.Vector3(...nb.center.toArray()).add(new T.Vector3(0,0,shaftLength*2)),shaftLength,0xffd478,shaftLength*.2,shaftLength*.1);layers.electrodes.add(arrow);
// Fit full source envelopes in the central 40% of actual local mesh AABBs.
// This is conservative display placement, NOT tissue registration or a biological containment claim.
const attachments=[], mapping={schema:'body-attached-schematic-1',anatomicalRegistration:false,independentClocks:true,sourceUnits:'um',bodyUnits:'mm',layers:{}};
function attach(names,meshName,envelope){
 const mesh=bodyMeshes.find(m=>m.local&&m.o.userData.meshName.endsWith(meshName));
 if(!mesh){names.forEach(k=>{layers[k].visible=false;mapping.layers[k]={available:false,reason:'Required local body mesh missing'};});return;}
 mesh.o.geometry.computeBoundingBox();const target=mesh.o.geometry.boundingBox.clone();const {center,safe,scale,sourceCenter}=Workbench.transforms.fit(envelope,target);
 const anchor=new T.Group();rig.add(anchor);
 names.forEach(k=>{anchor.add(layers[k]);layers[k].scale.setScalar(scale);layers[k].position.copy(center).addScaledVector(sourceCenter,-scale);mapping.layers[k]={available:true,segmentIndex:mesh.index,segmentName:nodeData[mesh.index]?.name,meshName:mesh.o.userData.meshName,displayScale:scale,worldMmPerSourceUm:scale*.001,sourceCenterMm:sourceCenter.toArray(),sourceEnvelopeMm:{min:envelope.min.toArray(),max:envelope.max.toArray()},meshLocalBoundsMm:{min:target.min.toArray(),max:target.max.toArray()},safeLocalBoundsMm:{min:safe.min.toArray(),max:safe.max.toArray()},localTranslationMm:layers[k].position.toArray(),placement:'schematic similarity; not anatomical registration'};});
 attachments.push({anchor,index:mesh.index,names});
}
scene.updateMatrixWorld(true);const neuralEnvelope=new T.Box3().setFromObject(layers.neural).union(new T.Box3().setFromObject(layers.electrodes));
// Include the complete retracted shafts at depth=0, not only the initial insertion state.
electrodeObjects.forEach(o=>{const box=new T.Box3().setFromObject(o);box.translate(new T.Vector3(0,0,shaftLength));neuralEnvelope.union(box);});
neuralEnvelope.expandByScalar(Math.max(electrodeDiameter/2,nb.size*.012));
attach(['neural','electrodes'],'/c_head',neuralEnvelope);
attach(['calcium'],'/c_abdomen12',cb.box.clone().expandByScalar(cb.size*.025));
neuralPoints.material.size*=mapping.layers.neural?.displayScale||1;calciumPoints.material.size*=mapping.layers.calcium?.displayScale||1;
worldLabel('neural',neuralEnvelope.getCenter(new T.Vector3()),'头部神经 / 电极 · 共享示意缩放');worldLabel('calcium',cb.center.clone(),'腹部上皮伤口 · 非脑钙波');
function updateAttachments(frame,idx){attachments.forEach(({anchor,index})=>{const p=good(frame?.[index])?frame[index]:nodeData[index]?.position;const q=list(B.rotations_wxyz)[idx]?.[index];Workbench.transforms.pose(anchor,p,q);});scene.updateMatrixWorld(true);}
function frames(data,key){return list(data[key]);}const af=frames(N,'activity'),cf=frames(C,'values'),bf=frames(B,'frames');
const activityAvailable=af.some(a=>list(a).some(v=>v!==null&&Number.isFinite(Number(v))));$('activation').disabled=!activityAvailable;$('activation').checked=activityAvailable;
function frameIndex(data,key){return Workbench.timeline.index(data,key,progress);}
function valueAt(data,key,i){const row=frames(data,key)[frameIndex(data,key)];const v=row&&row[i];return v!==null&&v!==undefined&&Number.isFinite(Number(v))?Number(v):null;}
function rangeOf(rows,excluded=[]){const vals=[];rows.forEach(r=>list(r).forEach((v,i)=>{if(!excluded[i]&&v!==null&&Number.isFinite(Number(v)))vals.push(Number(v));}));if(!vals.length)return [0,1];vals.sort((a,b)=>a-b);return [vals[Math.floor(vals.length*.02)],vals[Math.min(vals.length-1,Math.floor(vals.length*.98))]];}
const nr=rangeOf(af),cr=rangeOf(cf,list(C.ablated)),color=new T.Color();const calciumRanges={values:cr,er_values:rangeOf(frames(C,'er_values'),list(C.ablated)),ip3_values:rangeOf(frames(C,'ip3_values'),list(C.ablated)),damage:[0,1]};let calciumKey='values';const calciumLabel=element('label','钙模型变量 ',$('layer-calcium').parentNode.parentNode),calciumMode=element('select','',calciumLabel);calciumMode.id='calcium-variable';[['values','胞质 Ca / µM'],['er_values','ER Ca / µM（ER体积）'],['ip3_values','IP3 / µM'],['damage','损伤标记 / 无量纲']].forEach(([k,label])=>{if(list(C[k]).length){const o=element('option',label,calciumMode);o.value=k;}});calciumMode.onchange=()=>{calciumKey=calciumMode.value;updateData();};
function colorPoints(o,data,key,range,enabled){const attr=o.geometry.attributes.color;for(let i=0;i<attr.count;i++){const index=o.userData.indices[i];const val=key==='damage'?(Array.isArray(data.damage?.[0])?valueAt(data,key,index):data.damage?.[index]):valueAt(data,key,index);if(data===C&&list(C.ablated)[index])color.setHex(0x667079);else if(!enabled)color.setHex(0x4ebbd1);else Workbench.inspection.color(val,range,color,$('accessible-colors')?.checked);attr.setXYZ(i,color.r,color.g,color.b);}attr.needsUpdate=true;}
function timeDescription(data,key){const idx=frameIndex(data,key),t=list(data.times_s)[idx];return idx<0?'无动态帧':t!=null?finite(t).toPrecision(4)+' s · 帧 '+idx:'帧 '+idx+'（未提供秒时基）';}
function updateData(){colorPoints(neuralPoints,N,'activity',nr,$('activation').checked);colorPoints(calciumPoints,C,calciumKey,calciumRanges[calciumKey]||[0,1],true);const idx=frameIndex(B,'frames'),frame=bf[idx];if(frame){if(good(frame[1]))rig.position.copy(region.body).sub(bb.center).sub(new T.Vector3(...frame[1]).sub(bodyRoot));bodyObjects.forEach(o=>{if(good(frame[o.userData.index]))o.position.fromArray(frame[o.userData.index]);});bodyMeshes.forEach(m=>{if(m.local&&good(frame[m.index]))m.o.position.fromArray(frame[m.index]);const q=list(B.rotations_wxyz)[idx]?.[m.index];if(m.local&&Array.isArray(q)&&q.length===4)m.o.quaternion.set(q[1],q[2],q[3],q[0]);});const a=bodyLinks.geometry.attributes.position;let j=0;list(B.links).forEach(l=>{if(nodeData[l[0]]?.name!=='world'&&nodeData[l[1]]?.name!=='world'&&good(frame[l[0]])&&good(frame[l[1]])&&j+1<a.count){a.setXYZ(j++,...frame[l[0]]);a.setXYZ(j++,...frame[l[1]]);}});a.needsUpdate=true;}
updateAttachments(frame,idx);if(['neural','calcium'].includes(focusName)&&typeof orbit!=='undefined'){const box=new T.Box3().setFromObject(layers[focusName]);if(focusName==='neural')box.union(new T.Box3().setFromObject(layers.electrodes));try{const f=window.Workbench?.scene?.focusTargets?.()||[];f.forEach(o=>{if(o.visible)box.union(new T.Box3().setFromObject(o));});}catch(e){}if(!box.isEmpty()){orbit.target.copy(box.getCenter(new T.Vector3()));cameraUpdate();}}updateLegend();$('time').textContent=Math.round(progress*100)+'% · 回放';if(selected){syncSelection();inspect(selected);}}
function source(title,data,count){const box=element('div','',$('provenance'));box.className='source';element('b',title+' · '+count,box);element('span',txt(data.provenance||data.source||'来源未提供'),box);if(data.available===false||data.unavailable)element('span',' · 不可用：'+txt(data.unavailable||data.reason),box);}
source('身体',B,nodeData.length+' 节点');source('神经',N,neuralPos.length+' 点 / '+(activityAvailable?'含动态数据':'无每神经元活动'));if(activityAvailable)element('p','独立点神经元演示，非连接组/非实测',$('provenance')).className='warning';source('电极',E,electrodePos.length+' 通道');source('钙波（独立上皮）',C,calciumPos.length+' 点');
let benchData=D.bench||{};
function benchSummary(b){return '台架状态：'+(b.status||'未知')+' · 测量记录 '+(b.measurement_count??'未知')+' 条 · '+list(b.checks).filter(c=>c.status==='NOT_RUN').length+' 项未执行。评估检查输入，不证明物理器件验证。';}
$('bench').textContent=benchSummary(benchData);
const api=Workbench.service.api;
function fileInput(label,id,accept){const l=element('label',label,$('bench').parentNode),input=element('input','',l);input.type='file';input.id=id;input.accept=accept;return input;}
const configUpload=fileInput('台架配置 JSON（提交到项目服务）','bench-config','.json,application/json'),csvUpload=fileInput('原始测量 CSV（提交到项目服务）','bench-csv','.csv,text/csv'),evaluateButton=element('button','评估配置 + CSV',$('bench').parentNode);evaluateButton.id='bench-evaluate';
evaluateButton.onclick=async()=>{const configFile=configUpload.files[0],csvFile=csvUpload.files[0];if(!configFile||!csvFile){$('bench').textContent='请选择配置 JSON 和原始测量 CSV 两个文件。';return;}evaluateButton.disabled=true;try{if(configFile.size>2*1024*1024||csvFile.size>2*1024*1024)throw Error('每个输入限 2MB');const config=JSON.parse(await configFile.text());if(!config||typeof config!=='object'||Array.isArray(config))throw Error('配置必须为 JSON 对象');const report=await api('/api/bench/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({config,csv:await csvFile.text()})});benchData=report;$('bench').textContent='服务端评估：'+benchSummary(report);}catch(e){if(e.data?.status){benchData=e.data;$('bench').textContent='服务端拒绝输入：'+benchSummary(e.data);}else $('bench').textContent='评估失败（未获得通过结论）：'+e.message;}finally{evaluateButton.disabled=false;}};
const upload=fileInput('只读查看已有报告 JSON（不评估、不上传）','bench-report','.json,application/json');upload.onchange=async()=>{try{const f=upload.files[0];if(!f)return;if(f.size>2*1024*1024)throw Error('文件超过 2MB');const b=JSON.parse(await f.text());if(b.schema_version!=='bench-1.0'||!Array.isArray(b.checks))throw Error('不是 bench-1.0 报告');benchData=b;$('bench').textContent='只读外部报告（未核验，非服务评估）：'+benchSummary(b);}catch(e){$('bench').textContent='报告未导入：'+e.message;}};
const chain=element('section','',$('bench').parentNode.parentNode);element('h2','05 / 记录链检查',chain);['电极触点','界面阻抗','放大器','模拟滤波','ADC','数字处理'].forEach((name,i)=>{const button=element('button',name+(i<5?' →':''),chain);button.style.margin='3px';button.style.fontSize='11px';button.onclick=()=>{clearSelection();$('inspector').replaceChildren();dl([['记录链节点',name],['模型信息',D.bench?.chain?.[i]||'未提供逐节点参数'],['报告状态（未核验原始证据）',benchData.status||'NOT_RUN'],['对应检查',list(benchData.checks).filter(c=>[['impedance_magnitude','impedance_phase'],['impedance_magnitude','impedance_phase'],['input_noise_asd','reference_noise_asd','gain'],['phase','alias_rejection'],['saturation_input','alias_rejection'],['gain','phase']][i].includes(c.metric))],['限制','模型实现不等于物理器件通过验证']]);};});
element('p','身体回放为胸部根相对坐标，移除了记录轨迹平移；身体 / 神经 / 上皮均为独立时基。',chain).className='muted';
const captureLabel=element('label','',chain),capture=element('input','',captureLabel);capture.type='checkbox';element('span','50 µm 几何邻域（不是电场截断）',captureLabel);const captureMesh=new T.Mesh(new T.SphereGeometry(.05,20,12),new T.MeshBasicMaterial({color:0xe9c16f,wireframe:true,transparent:true,opacity:.25,depthWrite:false}));captureMesh.visible=false;scene.add(captureMesh);capture.id='capture-neighborhood';capture.onchange=()=>syncSelection();selectionRing.renderOrder=100;captureMesh.renderOrder=99;
const disabled={body:!nodeData.length&&!bodyMeshes.length,neural:!neuralPos.length||!mapping.layers.neural?.available,electrodes:!electrodePos.length||!mapping.layers.electrodes?.available,calcium:!calciumPos.length||!mapping.layers.calcium?.available};Object.keys(layers).forEach(k=>{const e=$('layer-'+k);e.disabled=disabled[k];e.checked=!disabled[k];layers[k].visible=e.checked;e.addEventListener('change',()=>{layers[k].visible=e.checked;if(selected&&selected.kind===k&&!e.checked)clearSelection();});});
$('status').textContent=missing?'未提供 data.js；空场景，不生成替代数据。':'本地数据已加载 · '+(activityAvailable?'激活按导入数值着色':'神经活动未提供：激活着色禁用')+' · 单一 3D 场景';
// Physical opacity and section plane are view aids only.
const controls=element('div','',$('transparent').parentNode.parentNode);const opLabel=element('label','身体不透明度 ',controls);const opacity=element('input','',opLabel);opacity.type='range';opacity.min='5';opacity.max='100';opacity.value='6';opacity.id='opacity';const clipLabel=element('label','剖切位置（仅视图） ',controls);const clip=element('input','',clipLabel);clip.type='range';clip.min='0';clip.max='100';clip.value='100';clip.id='clip';const plane=new T.Plane(new T.Vector3(0,0,-1),span*4);renderer.localClippingEnabled=true;
function updateOpacity(){const transparent=$('transparent').checked;bodyMats.forEach(m=>{m.opacity=transparent?Number(opacity.value)/100:1;m.depthWrite=!transparent;m.transparent=m.opacity<1;m.needsUpdate=true;});['neural','electrodes','calcium'].forEach(k=>layers[k].traverse(o=>{if(!o.material)return;const materials=Array.isArray(o.material)?o.material:[o.material];materials.forEach(m=>{m.transparent=transparent;m.depthTest=!transparent;m.opacity=transparent&&k==='electrodes' ? .4 : 1;m.needsUpdate=true;});o.renderOrder=transparent?(k==='electrodes'?10:20):0;}));bodyObjects.forEach(o=>{o.visible=!bodyMeshes.length;});bodyLinks.visible=!bodyMeshes.length;Workbench.layers.updateShell({meshes:bodyMeshes,materials:bodyMats,focus:focusName,transparent,opacity:Number(opacity.value)/100,localOnly:$('local-shell')?.checked});}opacity.oninput=updateOpacity;$('transparent').onchange=updateOpacity;clip.oninput=()=>{scene.updateMatrixWorld(true);const box=new T.Box3().setFromObject(['neural','calcium'].includes(focusName)?layers[focusName]:layers.body);const axis=plane.normal.x?'x':plane.normal.y?'y':'z';plane.constant=box.min[axis]+Number(clip.value)/100*(box.max[axis]-box.min[axis]);renderer.clippingPlanes=Number(clip.value)===100?[]:[plane];};
const layerControls=Workbench.layers.installControls(controls,()=>{renderer.setPixelRatio(layerControls.lowPower.checked?1:Math.min(window.devicePixelRatio||1,1.5));resize();updateOpacity();updateData();});
const clipAxisLabel=element('label','剖切方向 ',controls),clipAxis=element('select','',clipAxisLabel);clipAxis.id='clip-axis';['Z','X','Y'].forEach(axis=>{const o=element('option',axis,clipAxis);o.value=axis;});clipAxis.onchange=()=>{plane.normal.set(clipAxis.value==='X'?-1:0,clipAxis.value==='Y'?-1:0,clipAxis.value==='Z'?-1:0);clip.oninput();};
const numericLegend=element('div','',$('stage'));numericLegend.id='numeric-legend';numericLegend.className='numeric-legend';function updateLegend(){const r=calciumRanges[calciumKey]||[0,1];numericLegend.textContent='神经 '+nr.map(v=>Number(v).toPrecision(3)).join(' — ')+' Hz ｜ '+(calciumMode.selectedOptions[0]?.textContent||calciumKey)+' '+r.map(v=>Number(v).toPrecision(3)).join(' — ')+' ｜ 灰：缺失 / 暗灰：消融储库 · 色域2–98百分位（排除消融储库）';}
$('activation').onchange=updateData;$('insertion').onchange=()=>{arrow.visible=$('insertion').checked;};$('depth').oninput=()=>{const depth=Number($('depth').value)/100;electrodeObjects.forEach(o=>{o.position.z=o.userData.base[2]+shaftLength/2+(1-depth)*shaftLength;});if(selected){syncSelection();inspect(selected);}};
function dl(fields){const d=element('dl','',$('inspector'));fields.forEach(([k,v])=>{element('dt',k,d);element('dd',txt(v),d);});}
let inspectorSignature='';
function electrodeContact(i){const o=electrodeObjects.find(o=>o.userData.index===i);return o?o.position.clone().add(new T.Vector3(0,0,-shaftLength/2)):null;}
function selectionPosition(s){if(!s)return null;scene.updateMatrixWorld(true);if(s.kind==='electrodes'){const p=electrodeContact(s.index);return p?layers.electrodes.localToWorld(p):null;}const p=s.kind==='body'?(bf[frameIndex(B,'frames')]?.[s.index]||nodeData[s.index]?.position):({neural:neuralPos,calcium:calciumPos}[s.kind]||[])[s.index];return good(p)?layers[s.kind].localToWorld(new T.Vector3(...p.slice(0,3).map(v=>Number(v)*(s.kind==='body'?1:.001)))):null;}
function syncSelection(){const p=selectionPosition(selected);selectionRing.visible=!!p&&layers[selected.kind].visible&&renderer.clippingPlanes.every(plane=>plane.distanceToPoint(p)>=0);if(p){const scale=layers[selected.kind].getWorldScale(new T.Vector3()).x;selectionRing.position.copy(p);selectionRing.scale.setScalar(({body:bb.size*.018,neural:nb.size*.015,calcium:cb.size*.02,electrodes:electrodeDiameter})[selected.kind]*scale);captureMesh.position.copy(p);captureMesh.scale.setScalar(scale);}captureMesh.visible=selectionRing.visible&&capture.checked&&selected?.kind==='electrodes';}
function inspect(s){const signature=JSON.stringify([s,frameIndex(N,'activity'),frameIndex(C,calciumKey),frameIndex(B,'frames'),calciumKey,$('depth').value]);if(signature===inspectorSignature)return;inspectorSignature=signature;$('inspector').replaceChildren();const i=s.index;let fields=[],pos=null,group=null,scale=.01;
if(s.kind==='neural'){pos=neuralPos[i];group=layers.neural;scale=nb.size*.015;fields=[['神经元 ID',list(N.ids)[i]??i],['原始坐标 / µm',pos],['活动',valueAt(N,'activity',i)??'不可用（未推断或伪造）'],['膜电位 / mV',valueAt(N,'membrane_mV',i)??'未提供'],['单位',N.units||'未提供'],['独立时基',timeDescription(N,'activity')],['来源',N.provenance||'未提供']];}
if(s.kind==='calcium'){pos=calciumPos[i];group=layers.calcium;scale=cb.size*.02;fields=[['上皮细胞索引',i],['原始坐标 / µm',pos],['当前变量',calciumMode.selectedOptions[0]?.textContent||calciumKey],['变量值',calciumKey==='damage'?(Array.isArray(C.damage?.[0])?valueAt(C,'damage',i):C.damage?.[i]):valueAt(C,calciumKey,i)??'不可用'],['单位',C.units||'未提供'],['独立时基',timeDescription(C,'values')],['细胞状态',list(C.ablated_indices).includes(i)?'消融 / 储库：不代表存活细胞':list(C.ablated)[i]?'消融（导入标记）':'未提供存活验证'],['来源',C.provenance||'未提供'],['坐标系',C.coordinate_frame||'separate_epithelial_model']];}
if(s.kind==='body'){const n=nodeData[i]||{};pos=(bf[frameIndex(B,'frames')]||[])[i]||n.position;group=layers.body;scale=bb.size*.018;fields=[['身体节点',n.name||i],['原始坐标 / mm',pos],['半径 / mm',n.radius_mm??'未提供'],['独立时基',timeDescription(B,'frames')],['下降驱动 / Hz',list(B.descending_rate_hz)[frameIndex(B,'frames')]??'未提供'],['足部接触（不是神经活动）',list(B.contact_flags)[frameIndex(B,'frames')]||'未提供']];}
if(s.kind==='electrodes'){pos=electrodeContact(i)?.multiplyScalar(1000).toArray()||electrodePos[i];group=layers.electrodes;scale=electrodeDiameter;const distances=neuralPos.map((p,j)=>({index:j,d:good(p)?Math.hypot(p[0]-pos[0],p[1]-pos[1],p[2]-pos[2]):Infinity})).sort((a,b)=>a.d-b.d).slice(0,5);fields=[['电极通道',list(E.ids)[i]??i],['原始触点坐标 / µm',electrodePos[i]],['当前示意触点 / µm',pos],['真实直径 / µm',finite(E.diameter_um,7)],['设计间距 / µm',E.pitch_um??'未提供'],['示意插入进度',Number($('depth').value)+'% · 非验证手术'],['参考电极坐标 / µm',E.reference_um||'未提供'],['回流电极坐标 / µm',E.return_um||'未提供'],['近邻（同神经坐标框架）',distances.map(a=>String(list(N.ids)[a.index]??a.index)+' @ '+a.d.toFixed(1)+' µm').join('; ')||'无神经点'],['贡献 / 重叠', '仅几何距离；无逐源实测权重，不推断电位贡献'],['来源',E.provenance||'未提供']];}
if(s.kind==='electrodes')fields.push(['该通道台架证据',Workbench.inspection.channelEvidence(benchData,list(E.ids)[i]??i,i)]);if(mapping.layers[s.kind])fields.push(['身体附着 / 示意映射',mapping.layers[s.kind]],['世界显示坐标 / mm',selectionPosition(s)?.toArray()]);dl(fields);element('p','神经与电极共享均匀显示缩放，保留源几何 7 µm / 20 µm 比例；不是身体内真实尺寸或解剖配准。腹部为独立上皮伤口，非脑钙波。',$('inspector')).className='muted';
syncSelection();return fields;}
function select(kind,index){const lengths={neural:neuralPos.length,electrodes:electrodePos.length,calcium:calciumPos.length,body:nodeData.length};if(!Number.isInteger(index)||index<0||index>=lengths[kind])return false;selected={kind,index};electrodeObjects.forEach(o=>o.material.color.setHex(o.userData.index===index&&kind==='electrodes'?0xffffff:0xe5ba65));inspect(selected);syncSelection();return true;}
function clearSelection(){inspectorSignature='';selected=null;selectionRing.visible=false;captureMesh.visible=false;$('inspector').replaceChildren();element('p','点击对象查看导入数值。',$('inspector')).className='muted';electrodeObjects.forEach(o=>o.material.color.setHex(0xe5ba65));}$('clear').onclick=clearSelection;
const orbit={target:new T.Vector3(),distance:Math.max(nb.size*2.2,.2),theta:.2,phi:1.05};function cameraUpdate(){camera.position.copy(orbit.target).add(new T.Vector3(orbit.distance*Math.sin(orbit.phi)*Math.sin(orbit.theta),orbit.distance*Math.cos(orbit.phi),orbit.distance*Math.sin(orbit.phi)*Math.cos(orbit.theta)));camera.near=Math.max(orbit.distance/10000,.000001);camera.far=Math.max(orbit.distance*100,span*10);camera.updateProjectionMatrix();camera.lookAt(orbit.target);}
function focus(name){focusName=name;updateOpacity();scene.updateMatrixWorld(true);const box=new T.Box3();const names=name==='all'?Object.keys(layers):name==='neural'?['neural','electrodes']:[name];names.forEach(k=>{if(layers[k]?.visible)box.union(new T.Box3().setFromObject(layers[k]));});try{(window.Workbench?.scene?.focusTargets?.()||[]).forEach(o=>{if(o.visible)box.union(new T.Box3().setFromObject(o));});}catch(e){}if(box.isEmpty())box.copy(({body:bb,neural:nb,calcium:cb}[name]||nb).box);const sphere=box.getBoundingSphere(new T.Sphere());orbit.target.copy(sphere.center);const angle=Math.min(T.MathUtils.degToRad(camera.fov/2),Math.atan(Math.tan(T.MathUtils.degToRad(camera.fov/2))*camera.aspect));orbit.distance=Math.max(.02,sphere.radius/Math.sin(angle)*1.18);$('status').textContent='物理范围：身体 '+bb.size.toFixed(3)+' mm ｜ 神经 '+(nb.size*1000).toFixed(1)+' µm ｜ 上皮 '+(cb.size*1000).toFixed(1)+' µm · 身体内示意缩放（非解剖配准） · '+(activityAvailable?'独立点神经元演示，非连接组/非实测':'无神经活动');cameraUpdate();document.querySelectorAll('[data-focus]').forEach(b=>b.classList.toggle('active',b.dataset.focus===name));return name;}
document.querySelectorAll('[data-focus]').forEach(b=>b.onclick=()=>focus(b.dataset.focus));focus('all');
const pickLabel=element('label','选择过滤 ',$('clear').parentNode),pickFilter=element('select','',pickLabel);pickFilter.id='pick-filter';[['auto','自动（透明身体让位内部）'],['body','身体'],['neural','神经'],['electrodes','电极'],['calcium','腹部上皮']].forEach(([value,label])=>{const o=element('option',label,pickFilter);o.value=value;});
const canvas=renderer.domElement,ray=new T.Raycaster(),pointer=new T.Vector2();let drag=null;
canvas.onpointerdown=e=>{drag={x:e.clientX,y:e.clientY,ox:e.clientX,oy:e.clientY,moved:false};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.ox,e.clientY-drag.oy)>4)drag.moved=true;if(e.shiftKey||e.buttons===2){const right=new T.Vector3().setFromMatrixColumn(camera.matrixWorld,0),up=new T.Vector3().setFromMatrixColumn(camera.matrixWorld,1);orbit.target.addScaledVector(right,-dx*orbit.distance/canvas.clientHeight).addScaledVector(up,dy*orbit.distance/canvas.clientHeight);}else{orbit.theta-=dx*.007;orbit.phi=Math.max(.05,Math.min(Math.PI-.05,orbit.phi+dy*.007));}drag.x=e.clientX;drag.y=e.clientY;cameraUpdate();};
function pickAt(clientX,clientY){const r=canvas.getBoundingClientRect();pointer.set((clientX-r.left)/r.width*2-1,-(clientY-r.top)/r.height*2+1);scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);ray.setFromCamera(pointer,camera);const visible=o=>{let current=o;while(current){if(!current.visible)return false;current=current.parent;}return pickFilter.value==='auto'||o.userData.kind===pickFilter.value;},unclipped=p=>renderer.clippingPlanes.every(plane=>plane.distanceToPoint(p)>=0);const candidates=ray.intersectObjects(picks.filter(o=>!o.isPoints&&visible(o)),false).filter(h=>unclipped(h.point)).map(h=>({kind:h.object.userData.kind,index:h.object.userData.index,distance:h.distance,pixel:0}));
[neuralPoints,calciumPoints].filter(visible).forEach(o=>{const a=o.geometry.attributes.position;for(let i=0;i<a.count;i++){const p=new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld);if(!unclipped(p))continue;const view=p.clone().applyMatrix4(camera.matrixWorldInverse),ndc=p.clone().project(camera);if(view.z>=0||ndc.z< -1||ndc.z>1||Math.abs(ndc.x)>1||Math.abs(ndc.y)>1)continue;const px=r.left+(ndc.x+1)*r.width/2,py=r.top+(1-ndc.y)*r.height/2;const radius=Math.max(2,o.material.size*r.height/(4*Math.tan(T.MathUtils.degToRad(camera.fov/2))*(-view.z)));const dx=Math.abs(px-clientX),dy=Math.abs(py-clientY);if(dx<=radius&&dy<=radius)candidates.push({kind:o.userData.kind,index:o.userData.indices[i],distance:p.distanceTo(camera.position),pixel:Math.hypot(dx,dy)});}});
candidates.sort((a,b)=>(pickFilter.value==='auto'&&$('transparent').checked?Number(a.kind==='body')-Number(b.kind==='body'):0)||a.distance-b.distance||a.pixel-b.pixel);if(candidates.length)select(candidates[0].kind,candidates[0].index);return candidates[0]||null;}
canvas.onpointerup=e=>{if(drag&&!drag.moved&&e.button===0)pickAt(e.clientX,e.clientY);drag=null;};canvas.onpointercancel=()=>drag=null;canvas.oncontextmenu=e=>e.preventDefault();canvas.addEventListener('wheel',e=>{e.preventDefault();orbit.distance=Math.max(.002,Math.min(span*100,orbit.distance*Math.exp(e.deltaY*.001)));cameraUpdate();},{passive:false});
const dynamic=af.length>1||cf.length>1||bf.length>1;$('play').disabled=!dynamic;$('timeline').disabled=!dynamic;
let frameSignature='';function setProgress(p){progress=Math.max(0,Math.min(1,finite(p)));$('timeline').value=Math.round(progress*1000);$('time').textContent=Math.round(progress*100)+'% · 回放';const signature=[frameIndex(N,'activity'),frameIndex(C,calciumKey),frameIndex(B,'frames')].join(':');if(signature!==frameSignature){frameSignature=signature;updateData();}return progress;}$('timeline').oninput=()=>setProgress(Number($('timeline').value)/1000);$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'Ⅱ 暂停':'▶ 播放';};
function resize(){const r=$('viewport').getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);if(window.ResizeObserver)new ResizeObserver(resize).observe($('viewport'));resize();updateOpacity();updateData();focus('all');document.addEventListener('visibilitychange',()=>{lastTime=0;});
function render(now){requestAnimationFrame(render);const dt=lastTime?Math.min((now-lastTime)/1000,.1):0;lastTime=now;if(playing&&!document.hidden)setProgress((progress+dt*Number($('speed').value)/20)%1);if(selected)syncSelection();renderer.render(scene,camera);labels.forEach(l=>{const p=l.parent.localToWorld(l.pos.clone()).project(camera);const detail=l.name==='electrodes';l.e.style.display=focusName!=='all'&&focusName!=='body'&&(!detail||focusName==='neural'||focusName==='electrodes')&&layers[l.name].visible&&p.z>=-1&&p.z<=1&&Math.abs(p.x)<=1.15&&Math.abs(p.y)<=1.15?'block':'none';const half=Math.min(l.e.offsetWidth/2,canvas.clientWidth/2);l.e.style.left=Math.max(half+4,Math.min(canvas.clientWidth-half-4,(p.x+1)/2*canvas.clientWidth))+'px';l.e.style.top=Math.max(90,Math.min(canvas.clientHeight-70,(-p.y+1)/2*canvas.clientHeight-45))+'px';});}
const servicePanel=$('service-panel')||element('section','',document.querySelector('aside.right'));servicePanel.id='service-panel';element('h2','项目服务 / 预算记录任务',servicePanel);element('p','场景是已有数据回放，不是实时仿真。此按钮仅运行记录链预算作业，不重新导出身体或运行世界物理。',servicePanel).className='muted';const health=element('p','正在连接项目服务…',servicePanel),runButton=element('button','运行记录链预算',servicePanel),jobLog=element('pre','',servicePanel),recording=element('pre','',servicePanel);health.id='service-health';runButton.id='run-recording';jobLog.id='service-job-log';recording.id='recording-result';let requestBusy=false,pollTimer,recordingSignature='';
async function refreshService(){try{const status=await api('/api/status'),job=status.job||{};health.textContent='服务：'+(status.service||'已连接')+' · 作业：'+(job.state||'无')+' · 台架：'+(status.bench?.status||'未知');runButton.disabled=requestBusy||['running','queued','starting'].includes(job.state);jobLog.textContent=JSON.stringify(job,null,2);const signature=JSON.stringify([job.id,job.state]);if(signature!==recordingSignature){recordingSignature=signature;try{const result=await api('/api/recording');recording.textContent='最近记录链预算（不驱动场景）\n'+JSON.stringify({run_id:result.run_id,status:result.status,stale_result:result.stale_result,previous_run_id:result.previous_run_id,bands:result.bands,tests:result.tests},null,2);}catch(e){recording.textContent='记录结果暂不可用：'+e.message;}}}catch(e){health.textContent='服务不可用：'+e.message+' · 场景仍仅回放已加载数据';runButton.disabled=requestBusy;}finally{clearTimeout(pollTimer);pollTimer=setTimeout(refreshService,2500);}}
const cancelButton=element('button','取消当前任务',servicePanel);cancelButton.id='cancel-recording';cancelButton.onclick=async()=>{cancelButton.disabled=true;try{const s=await api('/api/status');if(s.job?.id)await api('/api/jobs/'+encodeURIComponent(s.job.id)+'/cancel',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await refreshService();}catch(e){jobLog.textContent='取消失败：'+e.message;}finally{cancelButton.disabled=false;}};
runButton.onclick=async()=>{requestBusy=true;runButton.disabled=true;try{const result=await api('/api/jobs/recording',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({idempotency_key:crypto.randomUUID()})});jobLog.textContent=JSON.stringify(result,null,2);}catch(e){jobLog.textContent='任务请求失败：'+e.message;}finally{requestBusy=false;refreshService();}};refreshService();window.addEventListener('pagehide',()=>clearTimeout(pollTimer));
Workbench.navigation.install({parent:document.querySelector('.modes').parentNode,orbit,cameraUpdate,focus,renderer,scene,metadata:window.VIEWER_METADATA,getState:()=>({progress,focus:focusName,selected,depth:Number($('depth').value),mapping}),setState:s=>{setProgress(s.progress);focus(s.focus);$('depth').value=s.depth;$('depth').oninput();if(s.selected)select(s.selected.kind,s.selected.index);}});element('p','数据版本：'+(window.VIEWER_MANIFEST?.run_id||'未知')+' · 来源哈希 '+(window.VIEWER_MANIFEST?.source_hash||'未知'),$('provenance')).className='muted';
requestAnimationFrame(render);window.viewerTest={orbit,cameraUpdate,scenePoints:{get neural(){return neuralPoints;},get calcium(){return calciumPoints;}},mapping,attachments,rig,bodyMeshes,electrodeObjects,shaftLength,pickFilter,selectionPosition,sourceToWorld(kind,positionUm){scene.updateMatrixWorld(true);return layers[kind]?.localToWorld(new T.Vector3(...positionUm).multiplyScalar(.001)).toArray();},setDepth(value){$('depth').value=Math.max(0,Math.min(100,finite(value)));$('depth').oninput();scene.updateMatrixWorld(true);return Number($('depth').value);},mappingDiagnostics(){scene.updateMatrixWorld(true);return attachments.map(({anchor,index,names})=>({segmentIndex:index,anchorWorldMatrix:anchor.matrixWorld.toArray(),layers:names.map(kind=>{const box=new T.Box3(),inverse=anchor.matrixWorld.clone().invert();layers[kind].traverse(o=>{const a=o.geometry?.attributes.position;if(a)for(let i=0;i<a.count;i++)box.expandByPoint(new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).applyMatrix4(inverse));});return {kind,worldMatrix:layers[kind].matrixWorld.toArray(),localGeometryBoundsMm:{min:box.min.toArray(),max:box.max.toArray()},...mapping.layers[kind]};})}));},layers,select,clearSelection,focus,setProgress,pickAt,selectionRing,captureMesh,get selected(){return selected;},get progress(){return progress;},get focusName(){return focusName;},counts:{body:nodeData.length,neural:neuralPos.length,electrodes:electrodePos.length,calcium:calciumPos.length},activityAvailable,renderer,scene,camera,project(kind,index){scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);const arr={body:nodeData.map(n=>n.position),neural:neuralPos,electrodes:electrodePos,calcium:calciumPos}[kind];if(!arr||!good(arr[index]))return null;const p=selectionPosition({kind,index}).project(camera);const r=canvas.getBoundingClientRect();return {x:r.left+(p.x+1)/2*r.width,y:r.top+(1-p.y)/2*r.height};}};window.viewerReady=true;
})();
